"""Recreate rent_data table

Revision ID: c8903837f3c7
Revises: 
Create Date: 2025-02-19 17:00:19.461011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8903837f3c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('rent_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rent_data_id'), 'rent_data', ['id'], unique=False)
    op.create_index(op.f('ix_rent_data_neighborhood'), 'rent_data', ['neighborhood'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rent_data_neighborhood'), table_name='rent_data')
    op.drop_index(op.f('ix_rent_data_id'), table_name='rent_data')
    op.drop_table('rent_data')
    # ### end Alembic commands ###
