name: GitGuardian Scan

on: [push, pull_request]

jobs:
  ggshield:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install GitGuardian CLI
        run: pip install ggshield

      - name: Set COMMIT_RANGE
        run: |
          if [ $(git rev-list --count HEAD) -gt 1 ]; then
            echo "COMMIT_RANGE=$(git rev-parse HEAD~1)..$(git rev-parse HEAD)" >> $GITHUB_ENV
          else
            echo "COMMIT_RANGE=$(git rev-parse HEAD)" >> $GITHUB_ENV
          fi

      - name: Run GitGuardian scan
        run: ggshield secret scan commit-range ${{ env.COMMIT_RANGE }}
        env:
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
